In [1]:
import torch

In [26]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([[4,5,6]])
torch.cat((a,b),dim=1)

tensor([[1, 2, 3, 4, 5, 6]])

In [42]:
a = torch.ones((3,4))
a = torch.tril(a)
a

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.]])

In [49]:
b = torch.rand_like(a)
b
b = torch.masked_fill(b,~a.bool(),-torch.inf)
b

tensor([[0.4931,   -inf,   -inf,   -inf],
        [0.8980, 0.4071,   -inf,   -inf],
        [0.4320, 0.0870, 0.2067,   -inf]])

In [51]:
torch.cuda.is_available()

False

In [71]:
a = torch.range(1,6)
# a = torch.ones(6)
a = a.reshape((2,3))

print(torch.transpose(a,1,0))
print(torch.transpose(a,0,1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


/var/folders/y5/ssh5ylsd4tv7wfmm_06fmrqw0000gp/T/ipykernel_27865/1359759846.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(1,6)


In [85]:
a = torch.rand((2,1,4,1,3))
a = a.squeeze(dim=0)
a.shape

torch.Size([2, 1, 4, 1, 3])

In [88]:

a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

result = torch.matmul(a, b)

print(result)
print(a * b)
print(a @ b)

tensor([[19., 22.],
        [43., 50.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[19., 22.],
        [43., 50.]])


In [107]:
emb = torch.nn.Embedding(10, 25)

emb
r = emb(torch.tensor([0,1,2]))
r.shape
# r

torch.Size([3, 25])

In [117]:
drop = torch.nn.Dropout(0.5,False)
x = torch.randn(2, 2)
print(drop(x))
print(x)

tensor([[-0.0000,  0.0000],
        [ 0.0000, -1.2852]])
tensor([[-1.3127,  0.8687],
        [ 0.9203, -0.6426]])
