In [2]:
import numpy as np

In [3]:
from matplotlib import axis


a = np.array([[2,4],[3,1]])


In [4]:
print(np.sort(a,axis=-1))
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))
print(np.sort(a,axis=None))
print(np.sort(a,axis=2))

[[2 4]
 [1 3]]
[[2 1]
 [3 4]]
[[2 4]
 [1 3]]
[1 2 3 4]


AxisError: axis 2 is out of bounds for array of dimension 2