In [1]:
import numpy as np

In [6]:


x = np.linspace(-5, 5, 2)  # 生成一个一维数组，从-5到5，共10个元素
y = np.linspace(-5, 5, 2)  # 同上

print(x)
print(y)

X, Y = np.meshgrid(x, y)    # 使用meshgrid生成二维网格

print(X)
print(Y)


[-5.  5.]
[-5.  5.]
[[-5.  5.]
 [-5.  5.]]
[[-5. -5.]
 [ 5.  5.]]


In [ ]:
from matplotlib import axis


a = np.array([[2,4],[3,1]])


In [ ]:
print(np.sort(a,axis=-1))
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))
print(np.sort(a,axis=None))
print(np.sort(a,axis=2))

In [3]:
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [4]:
np.pad(a, (2, 3), 'edge')

array([1, 1, 1, 2, 3, 4, 5, 5, 5, 5])

In [10]:
p = np.random.randint(5, size=(10, 1))
# print(p.shape)
print(p)
# print(np.sort(p,axis=-1))
print(np.sort(p,axis=0))
# print(np.sort(p,axis=1))



[[2]
 [0]
 [2]
 [1]
 [0]
 [2]
 [4]
 [0]
 [2]
 [3]]
[[0]
 [0]
 [0]
 [1]
 [2]
 [2]
 [2]
 [2]
 [3]
 [4]]
